# Generated by Django 5.1.6 on 2025-04-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts_app', '0003_usuario_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='CustomUser',
        ),
    ]
